In [1]:
import numpy as np

# One-dimensional arrays

In [3]:
# create array of zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
# create array of ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
# to define size and value with which to fill
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [12]:
# create numpy array out of python one
arr = np.array([3, 1, 6, 7, 3, 653, 9])
arr

array([  3,   1,   6,   7,   3, 653,   9])

In [13]:
arr[4]

3

In [15]:
arr[1] = 2
arr

array([  3,   2,   6,   7,   3, 653,   9])

In [16]:
# create range of particular size
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [19]:
# array in the range of a particular size
np.linspace(2, 15, 10)

array([ 2.        ,  3.44444444,  4.88888889,  6.33333333,  7.77777778,
        9.22222222, 10.66666667, 12.11111111, 13.55555556, 15.        ])

# Multi-dimensional arrays

In [20]:
# specify dimensions of an array: rows & cols
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
arr = np.array([
    [3, 5, 1, 6],
    [6, 2, 10, 54],
    [54, 75, 1, 0]
])

arr

array([[ 3,  5,  1,  6],
       [ 6,  2, 10, 54],
       [54, 75,  1,  0]])

In [24]:
arr[1][2]

10

In [25]:
arr[2][1] = 55
arr

array([[ 3,  5,  1,  6],
       [ 6,  2, 10, 54],
       [54, 55,  1,  0]])

In [26]:
arr[1]

array([ 6,  2, 10, 54])

In [27]:
# get only particular columns
arr[:, 2]

array([ 1, 10,  1])

In [29]:
arr[:, 1] = [101, 102, 103]
arr

array([[  3, 101,   1,   6],
       [  6, 102,  10,  54],
       [ 54, 103,   1,   0]])

In [30]:
# generate random arrays
np.random.rand(5, 2)

array([[0.06659575, 0.70433229],
       [0.1239048 , 0.98631205],
       [0.64725463, 0.54820955],
       [0.14655424, 0.95934664],
       [0.17838729, 0.01946963]])

In [31]:
# to make random numbers repeatable
np.random.seed(5)
np.random.rand(4, 3)

array([[0.22199317, 0.87073231, 0.20671916],
       [0.91861091, 0.48841119, 0.61174386],
       [0.76590786, 0.51841799, 0.2968005 ],
       [0.18772123, 0.08074127, 0.7384403 ]])

In [33]:
# if we want to take numbers from standard normal distribution
np.random.seed(9)
np.random.randn(5, 2)

array([[ 1.10855471e-03, -2.89544069e-01],
       [-1.11606630e+00, -1.28827567e-02],
       [-3.78361464e-01, -4.81135363e-01],
       [-1.51733118e+00, -4.90871981e-01],
       [-2.40680579e-01, -6.47947460e-01]])

In [34]:
np.random.seed(7)
np.random.randint(low=2, high=54, size=(5, 2))

array([[49,  6],
       [27,  5],
       [21, 25],
       [41, 30],
       [16, 25]])

In [35]:
# we can multiply every element by particular data
100 * np.random.rand(4, 3)

array([[50.11204637,  7.20511334, 26.84389801],
       [49.98825008, 67.92299961, 80.37390361],
       [38.09411331,  6.59363469, 28.81455993],
       [90.95935277, 21.33853536, 45.21239618]])

# Elementwise operations

In [36]:
array = np.arange(5)
array

array([0, 1, 2, 3, 4])

In [37]:
array + 2

array([2, 3, 4, 5, 6])

In [38]:
array / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [41]:
array2 = 10 + (array * 10)

In [42]:
array2 + array

array([10, 21, 32, 43, 54])

# Comparision operations

In [44]:
array > 2

array([False, False, False,  True,  True])

In [45]:
array2 > array

array([ True,  True,  True,  True,  True])

In [46]:
# to see which elemnts are greater, not plain True/False
array2[array2 > array]

array([10, 20, 30, 40, 50])

# Summarizing operations

In [47]:
array.min()

0

In [48]:
array2.max()

50

In [49]:
array2.sum()

150

In [50]:
array.mean()

2.0

In [51]:
array.std()

1.4142135623730951

In [53]:
new_arr = np.random.rand(3, 5)
new_arr

array([[0.93120602, 0.02489923, 0.60054892, 0.9501295 , 0.23030288],
       [0.54848992, 0.90912837, 0.13316945, 0.52341258, 0.75040986],
       [0.66901324, 0.46775286, 0.20484909, 0.49076589, 0.37238469]])

In [54]:
new_arr.sum()

7.806462493198735