In [2]:
import numpy as np

# One-dimensional arrays

In [3]:
# create array of zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
# create array of ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
# to define size and value with which to fill
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [12]:
# create numpy array out of python one
arr = np.array([3, 1, 6, 7, 3, 653, 9])
arr

array([  3,   1,   6,   7,   3, 653,   9])

In [13]:
arr[4]

3

In [15]:
arr[1] = 2
arr

array([  3,   2,   6,   7,   3, 653,   9])

In [16]:
# create range of particular size
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [19]:
# array in the range of a particular size
np.linspace(2, 15, 10)

array([ 2.        ,  3.44444444,  4.88888889,  6.33333333,  7.77777778,
        9.22222222, 10.66666667, 12.11111111, 13.55555556, 15.        ])

# Multi-dimensional arrays

In [20]:
# specify dimensions of an array: rows & cols
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
arr = np.array([
    [3, 5, 1, 6],
    [6, 2, 10, 54],
    [54, 75, 1, 0]
])

arr

array([[ 3,  5,  1,  6],
       [ 6,  2, 10, 54],
       [54, 75,  1,  0]])

In [24]:
arr[1][2]

10

In [25]:
arr[2][1] = 55
arr

array([[ 3,  5,  1,  6],
       [ 6,  2, 10, 54],
       [54, 55,  1,  0]])

In [26]:
arr[1]

array([ 6,  2, 10, 54])

In [27]:
# get only particular columns
arr[:, 2]

array([ 1, 10,  1])

In [29]:
arr[:, 1] = [101, 102, 103]
arr

array([[  3, 101,   1,   6],
       [  6, 102,  10,  54],
       [ 54, 103,   1,   0]])

In [30]:
# generate random arrays
np.random.rand(5, 2)

array([[0.06659575, 0.70433229],
       [0.1239048 , 0.98631205],
       [0.64725463, 0.54820955],
       [0.14655424, 0.95934664],
       [0.17838729, 0.01946963]])

In [31]:
# to make random numbers repeatable
np.random.seed(5)
np.random.rand(4, 3)

array([[0.22199317, 0.87073231, 0.20671916],
       [0.91861091, 0.48841119, 0.61174386],
       [0.76590786, 0.51841799, 0.2968005 ],
       [0.18772123, 0.08074127, 0.7384403 ]])

In [33]:
# if we want to take numbers from standard normal distribution
np.random.seed(9)
np.random.randn(5, 2)

array([[ 1.10855471e-03, -2.89544069e-01],
       [-1.11606630e+00, -1.28827567e-02],
       [-3.78361464e-01, -4.81135363e-01],
       [-1.51733118e+00, -4.90871981e-01],
       [-2.40680579e-01, -6.47947460e-01]])

In [34]:
np.random.seed(7)
np.random.randint(low=2, high=54, size=(5, 2))

array([[49,  6],
       [27,  5],
       [21, 25],
       [41, 30],
       [16, 25]])

In [35]:
# we can multiply every element by particular data
100 * np.random.rand(4, 3)

array([[50.11204637,  7.20511334, 26.84389801],
       [49.98825008, 67.92299961, 80.37390361],
       [38.09411331,  6.59363469, 28.81455993],
       [90.95935277, 21.33853536, 45.21239618]])

# Elementwise operations

In [36]:
array = np.arange(5)
array

array([0, 1, 2, 3, 4])

In [37]:
array + 2

array([2, 3, 4, 5, 6])

In [38]:
array / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [41]:
array2 = 10 + (array * 10)

In [42]:
array2 + array

array([10, 21, 32, 43, 54])

# Comparision operations

In [44]:
array > 2

array([False, False, False,  True,  True])

In [45]:
array2 > array

array([ True,  True,  True,  True,  True])

In [46]:
# to see which elemnts are greater, not plain True/False
array2[array2 > array]

array([10, 20, 30, 40, 50])

# Summarizing operations

In [47]:
array.min()

0

In [48]:
array2.max()

50

In [49]:
array2.sum()

150

In [50]:
array.mean()

2.0

In [51]:
array.std()

1.4142135623730951

In [53]:
new_arr = np.random.rand(3, 5)
new_arr

array([[0.93120602, 0.02489923, 0.60054892, 0.9501295 , 0.23030288],
       [0.54848992, 0.90912837, 0.13316945, 0.52341258, 0.75040986],
       [0.66901324, 0.46775286, 0.20484909, 0.49076589, 0.37238469]])

In [54]:
new_arr.sum()

7.806462493198735

# Multiplication

In [12]:
u = np.arange(1,7)
v = np.arange(3,9)

In [13]:
u.shape, v.shape

((6,), (6,))

In [14]:
def vector_multplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    result = 0
    shape = u.shape[0]
    for i in range(shape):
        result += u[i] * v[i]
    
    return result

In [15]:
vector_multplication(u, v)

133

In [16]:
# analog of the one we did above is dot()
u.dot(v)

133

In [25]:
arr = np.random.rand(5,4)
arr

array([[0.90969502, 0.72492919, 0.06097546, 0.61336228],
       [0.98125557, 0.05038929, 0.36204099, 0.78622776],
       [0.71849521, 0.24262338, 0.67413969, 0.5627456 ],
       [0.79831637, 0.3811175 , 0.61071928, 0.72627451],
       [0.09863846, 0.11702187, 0.59105956, 0.91169733]])

In [24]:
arr2 = np.random.rand(4,1)
arr2

array([[0.65467089],
       [0.8640165 ],
       [0.00112854],
       [0.228264  ]])

In [ ]:
[0.65467089]    [0.90969502, 0.72492919, 0.06097546, 0.61336228]  
[0.8640165 ]    [0.98125557, 0.05038929, 0.36204099, 0.78622776]
[0.00112854]    [0.71849521, 0.24262338, 0.67413969, 0.5627456 ]
[0.228264  ]    [0.79831637, 0.3811175 , 0.61071928, 0.72627451]
                [0.09863846, 0.11702187, 0.59105956, 0.91169733]
    
take row from matrix (right), then transpose and then multiply. After that sum.

In [26]:
arr.dot(arr2)

array([[1.36197897],
       [0.86581271],
       [0.80922386],
       [1.01839784],
       [0.37445926]])

In [36]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    rows = U.shape[0]
    result = np.zeros(rows)
    
    for i in range(rows):
        result[i] = vector_multplication(U[i], v)
    
    return result

In [37]:
matrix_vector_multiplication(arr, arr2)

array([1.36197897, 0.86581271, 0.80922386, 1.01839784, 0.37445926])

In [38]:
arr.dot(arr2)

array([[1.36197897],
       [0.86581271],
       [0.80922386],
       [1.01839784],
       [0.37445926]])

In [39]:
# matrix-matrix multiplication
arr = np.random.rand(3, 4)
arr

array([[0.89243533, 0.12410723, 0.04428137, 0.62124557],
       [0.61834981, 0.14940746, 0.69118653, 0.27252122],
       [0.64132804, 0.23808549, 0.38230005, 0.04094243]])

In [40]:
arr2 = np.random.rand(4, 3)
arr2

array([[0.38636967, 0.24215796, 0.21396919],
       [0.2764935 , 0.96289938, 0.66580138],
       [0.74811041, 0.3835186 , 0.59052354],
       [0.29541681, 0.19184521, 0.67754385]])

In [41]:
arr.dot(arr2)

array([[0.59577853, 0.47177882, 0.72065474],
       [0.877813  , 0.61096746, 0.8245905 ],
       [0.61171653, 0.53902885, 0.54923956]])

In [42]:
def matrix_matrix_mult(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.ones((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [43]:
matrix_matrix_mult(arr, arr2)

array([[0.59577853, 0.47177882, 0.72065474],
       [0.877813  , 0.61096746, 0.8245905 ],
       [0.61171653, 0.53902885, 0.54923956]])

In [44]:
arr.dot(arr2)

array([[0.59577853, 0.47177882, 0.72065474],
       [0.877813  , 0.61096746, 0.8245905 ],
       [0.61171653, 0.53902885, 0.54923956]])

# Identity matrix

In [71]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
arr.dot(np.eye(4))

array([[0.89243533, 0.12410723, 0.04428137, 0.62124557],
       [0.61834981, 0.14940746, 0.69118653, 0.27252122],
       [0.64132804, 0.23808549, 0.38230005, 0.04094243]])

In [73]:
arr_square = np.array([[4, 6, 1],
                      [8, 12, 76],
                      [54, 21, 9]])
arr_square

array([[ 4,  6,  1],
       [ 8, 12, 76],
       [54, 21,  9]])

In [74]:
invert = np.linalg.inv(arr_square)
invert

array([[-0.08378378, -0.00185811,  0.025     ],
       [ 0.22702703, -0.00101351, -0.01666667],
       [-0.02702703,  0.01351351, -0.        ]])

In [76]:
I = invert.dot(arr_square)
I

array([[ 1.00000000e+00, -2.77555756e-17,  3.88578059e-16],
       [ 1.11022302e-16,  1.00000000e+00, -1.05471187e-15],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [77]:
arr_square.dot(I)

array([[ 4.,  6.,  1.],
       [ 8., 12., 76.],
       [54., 21.,  9.]])